[package]
name = "app"
version = "0.0.0"
authors = ["Michal Hornick√Ω <semtexzv@gmail.com>"]
edition = "2018"

[dependencies.common]
path = "../common"

[dependencies]
clap = "*"
serde = "*"

futures-util = { path ="../deps/futures-util" }

actix-web-async-await = { path = "../deps/actix-web-async-await"}


actix-comm = { path = "../deps/actix-comm" }
actix-arch = { path = "../deps/actix-arch" }
strat-eval = { path = "../deps/strat-eval"}

apis = { path = "../deps/apis" }
db = { path = "../deps/db" }

radix_trie = "*"
anymap = "*"
