[package]
name = "dp"
version = "0.0.0"
authors = ["Michal Hornick√Ω <semtexzv@gmail.com>"]

[dependencies.common]
path = "./common"

[dependencies]
clap = "*"
actix-net = { path = "./deps/actix-net" }
actix-arch = { path = "./deps/actix-arch" }
