[package]
name = "actix-net"
version = "0.0.0"
authors = ["Michal Hornick√Ω <semtexzv@gmail.com>"]
edition = "2018"

[dependencies.common]
path = "../../common"


[dependencies]
serde = "1.0"
zmq = { git = "https://github.com/semtexzv/rust-zmq" } #"0.9"
tokio-zmq = { git = "https://github.com/semtexzv/tokio-zmq"} #"0.5.2"
futures = "0.1.24"
tokio = "0.1"
failure = "*"
uuid = { version = "*", features = ["v4","serde"] }
nix = "*"