[package]
name = "actix-arch"
version = "0.0.0"
authors = ["Michal Hornick√Ω <semtexzv@gmail.com>"]
edition = "2018"

[dependencies.common]
path = "../../common"

[dependencies]
serde = "*"
actix-comm = { path = "../actix-comm"}
actix="*"
actix_derive = "*"